### ISSUE TITLE
Clarification Needed: Gemspec Dependency Range vs. Faraday Compatibility

### ISSUE THREAD

**Issue by srividb01** [AssemblyAI/assemblyai-ruby-sdk#11]
Hello Team,

I noticed that in the gemspec, Faraday is specified to be greater than 1.10, however, the assemblyai gem seems to require Faraday version 2.7 and above. Is this intentional? It appears there might be a discrepancy between the specified dependency range and the actual compatibility with Faraday versions. Could you please clarify this issue?

Thank you.

**Comment by armandobelardo** [comment]
Hi there @srividb01 I believe the discrepancy between the repo and rubygems.org was due to a release of the gem not having happened! 
You should be set with the new release from today: https://rubygems.org/gems/assemblyai/versions/1.0.0.pre.beta.2
