### ISSUE TITLE
Uninitialized constant error since 1.0.0-beta.12+

### ISSUE THREAD

**Issue by ronb54** [AssemblyAI/assemblyai-ruby-sdk#38]
Hi there!

Since updating to `1.0.0-beta.12` and beyond, the error below started to show up:
```
NameError: uninitialized constant AssemblyAI::Gemconfig (NameError)

        "X-Fern-SDK-Version": AssemblyAI::Gemconfig::VERSION,
```

Not sure if I missed anything on the config or a step from the README. Let me know otherwise if you need more details as well. Thanks!

**Comment by Swimburger** [comment]
@ronb54 thank you for reporting! This should be fixed in the latest version.
