### ISSUE TITLE
AssemblyAI incompatible with Rails 7.2 Browser Block

### ISSUE THREAD

**Issue by beseku** [AssemblyAI/assemblyai-ruby-sdk#48]
Adding the AssemblyAI gem to a fresh Rails 7.2 install causes an "uninitialized constant ActionController::AllowBrowser::BrowserBlocker::UserAgent" exception when loading any controller that uses the (now default) Browser Block functionality.

Reproduced with a fresh rails install with no other gems added.

**Comment by Swimburger** [comment]
This issue has been fixed in 1.0.1. Can you try the new version?
https://rubygems.org/gems/assemblyai

**Comment by beseku** [comment]
Yes, this works now.
